name: Keep Alive (Native)

on:
  schedule:
    - cron: '0 0 */40 * *' # 每 40 天运行一次
  workflow_dispatch: # 👈 必须加上这一行，专门用来开启手动运行按钮

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      
      - name: Create Empty Commit
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit --allow-empty -m "chore: keep repository active to prevent workflow suspension"
          git push
